api:
    resource: "../src/Controller/"
    type: attribute
    prefix: /api

frontend:
    path: /{route}
    controller: App\Controller\FrontendController::index
    requirements:
        route: .*
